version: '3.3'
services:
  nginx:
    image: nginx:latest
    environment:
      PGID: '911'
      PUID: '911'
      TZ: Europe/Amsterdam
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.nginx-http.middlewares: https-redirect
        traefik.http.routers.nginx-https.middlewares: 500error@file
        traefik.http.routers.nginx-http.entrypoints: http
        traefik.http.services.nginx.loadbalancer.server.port: '80'
        traefik.http.routers.nginx-https.tls.certresolver: le
        traefik.constraint-label: traefik-public
        traefik.http.routers.nginx-https.entrypoints: https
        traefik.http.routers.nginx-http.rule: Host(`nginx.vnerd.nl`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.nginx-https.tls: 'true'
        traefik.http.routers.nginx-https.rule: Host(`nginx.vnerd.nl`)
        # traefik.http.middlewares.500error.plugin.staticresponse: 500error@file
        # traefik.http.middlewares.500error.plugin.staticresponse.StatusCode: '418'
        # traefik.http.middlewares.500error.plugin.staticresponse.Body: 'I'm a teapot'
        # traefik.http.middlewares.500error.plugin.staticresponse.Headers.X-Secret-Header: 'donttell,anyone,please'
      placement:
        constraints:
         - node.labels.Arch==i686
networks:
  traefik-public:
    external: true
